//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperA_Web.PaperA_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/PaperA_Service")]
    [System.SerializableAttribute()]
    public partial class MenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OnSpecialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OnSpecial {
            get {
                return this.OnSpecialField;
            }
            set {
                if ((this.OnSpecialField.Equals(value) != true)) {
                    this.OnSpecialField = value;
                    this.RaisePropertyChanged("OnSpecial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/PaperA_Service")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Persons {
            get {
                return this.PersonsField;
            }
            set {
                if ((this.PersonsField.Equals(value) != true)) {
                    this.PersonsField = value;
                    this.RaisePropertyChanged("Persons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaperA_Service.IPaperAService")]
    public interface IPaperAService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/GetMenuItems", ReplyAction="http://tempuri.org/IPaperAService/GetMenuItemsResponse")]
        PaperA_Web.PaperA_Service.MenuItem[] GetMenuItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/GetMenuItems", ReplyAction="http://tempuri.org/IPaperAService/GetMenuItemsResponse")]
        System.Threading.Tasks.Task<PaperA_Web.PaperA_Service.MenuItem[]> GetMenuItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/GetMenuItem", ReplyAction="http://tempuri.org/IPaperAService/GetMenuItemResponse")]
        PaperA_Web.PaperA_Service.MenuItem GetMenuItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/GetMenuItem", ReplyAction="http://tempuri.org/IPaperAService/GetMenuItemResponse")]
        System.Threading.Tasks.Task<PaperA_Web.PaperA_Service.MenuItem> GetMenuItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/Book_Reservation", ReplyAction="http://tempuri.org/IPaperAService/Book_ReservationResponse")]
        string Book_Reservation(PaperA_Web.PaperA_Service.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/Book_Reservation", ReplyAction="http://tempuri.org/IPaperAService/Book_ReservationResponse")]
        System.Threading.Tasks.Task<string> Book_ReservationAsync(PaperA_Web.PaperA_Service.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/GetReservation", ReplyAction="http://tempuri.org/IPaperAService/GetReservationResponse")]
        PaperA_Web.PaperA_Service.Reservation GetReservation(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/GetReservation", ReplyAction="http://tempuri.org/IPaperAService/GetReservationResponse")]
        System.Threading.Tasks.Task<PaperA_Web.PaperA_Service.Reservation> GetReservationAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/Update_Reservation", ReplyAction="http://tempuri.org/IPaperAService/Update_ReservationResponse")]
        string Update_Reservation(PaperA_Web.PaperA_Service.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperAService/Update_Reservation", ReplyAction="http://tempuri.org/IPaperAService/Update_ReservationResponse")]
        System.Threading.Tasks.Task<string> Update_ReservationAsync(PaperA_Web.PaperA_Service.Reservation reservation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaperAServiceChannel : PaperA_Web.PaperA_Service.IPaperAService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaperAServiceClient : System.ServiceModel.ClientBase<PaperA_Web.PaperA_Service.IPaperAService>, PaperA_Web.PaperA_Service.IPaperAService {
        
        public PaperAServiceClient() {
        }
        
        public PaperAServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaperAServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaperAServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaperAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PaperA_Web.PaperA_Service.MenuItem[] GetMenuItems() {
            return base.Channel.GetMenuItems();
        }
        
        public System.Threading.Tasks.Task<PaperA_Web.PaperA_Service.MenuItem[]> GetMenuItemsAsync() {
            return base.Channel.GetMenuItemsAsync();
        }
        
        public PaperA_Web.PaperA_Service.MenuItem GetMenuItem(int id) {
            return base.Channel.GetMenuItem(id);
        }
        
        public System.Threading.Tasks.Task<PaperA_Web.PaperA_Service.MenuItem> GetMenuItemAsync(int id) {
            return base.Channel.GetMenuItemAsync(id);
        }
        
        public string Book_Reservation(PaperA_Web.PaperA_Service.Reservation reservation) {
            return base.Channel.Book_Reservation(reservation);
        }
        
        public System.Threading.Tasks.Task<string> Book_ReservationAsync(PaperA_Web.PaperA_Service.Reservation reservation) {
            return base.Channel.Book_ReservationAsync(reservation);
        }
        
        public PaperA_Web.PaperA_Service.Reservation GetReservation(string email) {
            return base.Channel.GetReservation(email);
        }
        
        public System.Threading.Tasks.Task<PaperA_Web.PaperA_Service.Reservation> GetReservationAsync(string email) {
            return base.Channel.GetReservationAsync(email);
        }
        
        public string Update_Reservation(PaperA_Web.PaperA_Service.Reservation reservation) {
            return base.Channel.Update_Reservation(reservation);
        }
        
        public System.Threading.Tasks.Task<string> Update_ReservationAsync(PaperA_Web.PaperA_Service.Reservation reservation) {
            return base.Channel.Update_ReservationAsync(reservation);
        }
    }
}
